spring.application.name=PrestamoDeLibrosREST

# Configuracion del puerto
server.port=8081

# Configuracion de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/prestamosrest_db?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=2312

spring.datasource.driver-class-name=org.postgresql.Driver

# Muestra las sentencias SQL que ejecuta Spring Data JDBC
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
# Muestra los valores que se pasan a los parámetros
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
