CREATE TABLE Author (
    idAuthor BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TYPE AvailabilityStatus AS ENUM ('AVAILABLE', 'UNAVAILABLE');

CREATE TABLE Book (
    idBook BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    charge BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    availability AvailabilityStatus NOT NULL,
    title VARCHAR(255) NOT NULL,
    idAuthor BIGINT NOT NULL,

    CONSTRAINT fkAuthor
            FOREIGN KEY (idAuthor)
            REFERENCES Author(idAuthor)
            ON DELETE RESTRICT
);

CREATE TABLE Genre (
    idGenre BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    genre VARCHAR(255) NOT NULL
);

CREATE TABLE BookGenre (
    idBookGenre BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idBook BIGINT NOT NULL,
    idGenre BIGINT NOT NULL,

    CONSTRAINT fkBook
        FOREIGN KEY (idBook)
        REFERENCES Book(idBook)
        ON DELETE CASCADE,

    CONSTRAINT fkGenre
        FOREIGN KEY (idGenre)
        REFERENCES Genre(idGenre)
);

CREATE TABLE Client (
    idClient BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    accountBalance BIGINT NOT NULL
);


CREATE TYPE LoanStatus AS ENUM ('PENDING', 'PAID');

CREATE TABLE Loan (
    idLoan BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    date Date NOT NULL,
    status LoanStatus NOT NULL,
    charge BIGINT NOT NULL,
    idBook BIGINT NOT NULL,
    idClient BIGINT NOT NULL,

    CONSTRAINT fkBook
            FOREIGN KEY (idBook)
            REFERENCES Book(idBook)
            ON DELETE RESTRICT,

    CONSTRAINT fkClient
                FOREIGN KEY (idClient)
                REFERENCES Client(idClient)
                ON DELETE RESTRICT
);

CREATE TYPE RoleType AS ENUM ('ADMIN', 'LIBRARIAN', 'USER');

CREATE TABLE DBUser (
    idUser BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role RoleType NOT NULL
);
